apiVersion: v1
kind: Pod
metadata:
  name: tensorflow
  labels:
    name: tensorflow
spec:
  volumes:
  - hostPath:
      path: /var/lib/nvidia-docker/volumes/nvidia_driver/384.90
    name: nvidia-driver
  - hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so
    name: libcuda-so
  - hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    name: libcuda-so-1
  - hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.384.90
    name: libcuda-so-384-90
  containers:
  - name:  tensorflow
    image: tensorflow/tensorflow:latest-gpu
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: 1
    volumeMounts:
    - name: nvidia-driver
      mountPath: /usr/local/nvidia
      readOnly: true
    - name: libcuda-so
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so
    - name: libcuda-so-1
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    - name: libcuda-so-384-90
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.384.90
---
kind: Service
apiVersion: v1
metadata:
  name: svc-tensorflow
  labels:
    name: svc-tensorflow
spec:
  type: NodePort
  ports:
    - port: 9069
      targetPort: 8888
      name: tensorflow
      protocol: TCP
  selector:
    name: tensorflow
