apiVersion: v1
kind: Pod
metadata:
  name: tensorflow
  namespace: sanadhi-test
  labels:
    name: tensorflow
spec:
  volumes:
  - hostPath:
      path: /usr/lib/nvidia-384/bin
    name: bin
  - hostPath:
      path: /usr/lib/nvidia-384
    name: lib
  # - hostPath:
  #     path: /var/lib/nvidia-docker/volumes/nvidia_driver/384.90
  #   name: nvidia-driver
  - hostPath:
      path: /usr/lib/x86_64-linux-gnu
    name: lib-linux-gnu
  containers:
  - name:  tensorflow
    image: tensorflow/tensorflow:latest-gpu-py3
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: 2
    # env:
    # - name: LD_LIBRARY_PATH
    #   value: "${LD_LIBRARY_PATH}:/usr/lib/nvidia-384"
    # - name: LIBRARY_PATH
    #   value: "${LIBRARY_PATH}:/usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu:/usr/lib/nvidia-384"
    volumeMounts:
    # - name: nvidia-driver
    #   mountPath: /usr/local/nvidia
    #   readOnly: true
    - name: lib-linux-gnu
      mountPath: /usr/lib/x86_64-linux-gnu
    - name: bin
      mountPath: /usr/local/nvidia/bin
    - name: lib
      mountPath: /usr/local/nvidia/lib
---
kind: Service
apiVersion: v1
metadata:
  name: svc-tensorflow
  namespace: sanadhi-test
  labels:
    name: svc-tensorflow
spec:
  type: NodePort
  ports:
    - port: 9069
      targetPort: 8888
      name: tensorflow
      protocol: TCP
  selector:
    name: tensorflow
