apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-3
  namespace: sanadhi-test
  labels:
    name: tensorflow-3
spec:
  volumes:
  - hostPath:
      path: /usr/lib/nvidia-384/bin
    name: bin
  - hostPath:
      path: /usr/lib/nvidia-384
    name: lib
  - hostPath:
      path: /shared
    name: shared
  # - hostPath:
  #     path: /var/lib/nvidia-docker/volumes/nvidia_driver/384.90
  #   name: nvidia-driver
  - hostPath:
      path: /usr/lib/x86_64-linux-gnu
    name: lib-linux-gnu
  containers:
  - name:  tensorflow-3
    image: sanadhis/dl-docker:gpu-py3
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8888
      protocol: TCP
    - containerPort: 6006
      protocol: TCP
    args: ["jupyter", "notebook", "--allow-root"]
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: 2
    # env:
    # - name: LD_LIBRARY_PATH
    #   value: "${LD_LIBRARY_PATH}:/usr/lib/nvidia-384"
    # - name: LIBRARY_PATH
    #   value: "${LIBRARY_PATH}:/usr/local/cuda/lib64:/usr/lib/x86_64-linux-gnu:/usr/lib/nvidia-384"
    volumeMounts:
    # - name: nvidia-driver
    #   mountPath: /usr/local/nvidia
    #   readOnly: true
    - name: lib-linux-gnu
      mountPath: /usr/lib/x86_64-linux-gnu
    - name: bin
      mountPath: /usr/local/nvidia/bin
    - name: lib
      mountPath: /usr/local/nvidia/lib
    - name: shared
      mountPath: /root/sharedfolder
---
kind: Service
apiVersion: v1
metadata:
  name: svc-tensorflow-3
  namespace: sanadhi-test
  labels:
    name: svc-tensorflow-3
spec:
  type: NodePort
  ports:
    - port: 9071
      targetPort: 8888
      name: tensorflow-3
      protocol: TCP
    - port: 9072
      targetPort: 6006
      name: tensorflow-5
      protocol: TCP
  selector:
    name: tensorflow-3
